"""added active to members

Revision ID: 14524c4db11e
Revises: dfb01d31550e
Create Date: 2020-11-29 12:08:09.062609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14524c4db11e'
down_revision = 'dfb01d31550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'active')
    # ### end Alembic commands ###
