"""adding in a owner to the league table

Revision ID: 1ea2428814ff
Revises: 7d4f8688fb12
Create Date: 2020-11-23 11:31:11.732788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea2428814ff'
down_revision = '7d4f8688fb12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('owner', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'leagues', 'users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.drop_column('leagues', 'owner')
    # ### end Alembic commands ###
