"""changed category owner to user_id

Revision ID: 2194b67b45eb
Revises: 92ecd5b64fa9
Create Date: 2020-11-24 11:01:19.740098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2194b67b45eb'
down_revision = '92ecd5b64fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('owner', sa.Integer(), nullable=False))
    op.drop_constraint('categories_user_id_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['owner'], ['id'])
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_user_id_fkey', 'categories', 'users', ['user_id'], ['id'])
    op.drop_column('categories', 'owner')
    # ### end Alembic commands ###
