"""adding in account

Revision ID: 4999448450cc
Revises: 826fcc17111c
Create Date: 2020-11-17 22:15:28.835331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4999448450cc'
down_revision = '826fcc17111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('users', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'accounts', ['account_id'], ['id'])
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'account_id')
    op.drop_table('accounts')
    # ### end Alembic commands ###
