"""added relation member point

Revision ID: 5758804eb428
Revises: c25075af72ba
Create Date: 2020-11-28 12:48:57.690506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5758804eb428'
down_revision = 'c25075af72ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('giver_id', sa.Integer(), nullable=False))
    op.add_column('points', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'points', 'members', ['giver_id'], ['id'])
    op.create_foreign_key(None, 'points', 'members', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_column('points', 'receiver_id')
    op.drop_column('points', 'giver_id')
    # ### end Alembic commands ###
