"""added fines association with points

Revision ID: 6967e53f0026
Revises: b8fb57544db0
Create Date: 2020-11-25 15:58:06.312783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6967e53f0026'
down_revision = 'b8fb57544db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('fine_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'points', 'fines', ['fine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points', type_='foreignkey')
    op.drop_column('points', 'fine_id')
    # ### end Alembic commands ###
