"""changed category owner to user_id

Revision ID: 92ecd5b64fa9
Revises: 30ab2b22cab6
Create Date: 2020-11-24 10:53:34.676726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ecd5b64fa9'
down_revision = '30ab2b22cab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('categories_owner_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.drop_column('categories', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_owner_fkey', 'categories', 'users', ['owner'], ['id'])
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
