"""removed nullable=false

Revision ID: dfb01d31550e
Revises: 5758804eb428
Create Date: 2020-11-28 13:03:21.967556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb01d31550e'
down_revision = '5758804eb428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'giver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('points', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points', 'receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('points', 'giver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
